UIAugmentedText
Added tag 'augmentedText' to the nwc.taglib.xml file to make it
usable (work in progress!). However, changing nwc.taglib.xml has
"subtle" effects in the docker container: The application will
not start because of:

'''
22-Dec-2020 14:49:55.905 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke
Servlet.service() for servlet [Faces Servlet] in context with path [/ui] threw exception
 java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.myfaces.config.FacesConfigurator.purgeConfiguration(FacesConfigurator.java:544)
        at org.apache.myfaces.config.FacesConfigurator.update(FacesConfigurator.java:474)
        [...]
'''

Changing the file times with 'touch' from within the ui docker container has
the same effect. This might be in conjunction with the docker container running in
time zone UTC, whereas development takes place at CET / CEST. Touching 'web.xml'
in the container might be sufficient to clarify the issue.